- name: Update packages
  when: ansible_os_family == 'Debian'
  apt:
    update-cache: yes
    upgrade: yes

- name: Install essential packages
  package: 
    name: "{{ packages }}"
    state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config # create variable

- name: Enable passwordless sudo for user {{ username }}
  lineinfile: 
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed # check variable if dest file was changed

- name: Clone the latest dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: /home/{{ username }}/Documents/dotfiles
    recursive: no
    force: yes

- name: Stow the dotfiles
  shell: cd /home/{{ username }}/Documents/dotfiles && stow -v -t /home/{{ username }} */
  register: stow_result
  changed_when: stow_result.stderr != ""

- name: Set the correct ownership for the user's home folder (not using ansible.builtin.file because of idempotency)
  shell:
    cmd: "chown -Rc {{ username }}:{{ username}} /home/{{ username }}"
    warn: false
  register: chown_status
  changed_when: chown_status.stdout != "changed ownership of '/home/{{ username }}/Documents/dotfiles/.git/index' from root:root to {{ username }}:{{ username }}\nchanged ownership of '/home/{{ username }}/Documents/dotfiles/.git/HEAD' from root:root to {{ username }}:{{ username }}\nchanged ownership of '/home/{{ username }}/Documents/dotfiles/.git/ORIG_HEAD' from root:root to {{ username }}:{{ username }}"

- name: Debug
  debug:
    # var: vars
    # var: chown_status